services:
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - ./backend/.env
  #   volumes:
  #     - ./backend:/usr/src/app
  #   depends_on:
  #     - db

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/usr/src/app
  #   depends_on:
  #     - backend
  #   environment:
  #     NEXT_PUBLIC_BACKEND_URL: http://localhost:3001/api
  #     NODE_ENV: production

  db:
    image: postgres:13
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
